version: 2.1

jobs:
  sonar_scan:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: SonarQube Scan
          command: |
            npm install -g sonarqube-scanner
            sonar-scanner \
              -Dsonar.projectKey=ST10090959_APDS7311POE-Task3-DeansExam \
              -Dsonar.organization=st10090959 \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login=$SONAR_TOKEN
workflows:
  version: 2
  sonar_workflow:
    jobs:
      - sonar_scan
